### PR TITLE
Refactor: libint-2.6

### LINKED ISSUE #547: Migrate to Libint 2.6.0
**Describe the feature you'd like**
The installation support for Libint 2.6.0 has significantly improved in respect to version 2.4.2. 

**Describe what the current code offers in relation to what it lacks**
The current 2.4.2 Libint support is affected by the Boost Preprocessor packaged by Libint 2.4.2. Libint 2.6.0 supports an additional install flag that should remedy this situation.

**Additional context**
I currently get the following error flags when naively interfacing to Libint 2.6.0:

```bash
/tmp/vsc40558/gqcp/dev/intel-2019b-Python-3.7.4/gqcp/gqcp/src/Basis/Integrals/Interfaces/LibintInterfacer.cpp(126): error: no suitable user-defined conversion from "const std::vector<double, std::allocator<double>>" to "libint2::svector<libint2::Shell::real_t={double}>" exists
      libint2::Shell::Contraction libint_contraction {libint_l, libint_pure, libint_coeff};
                                                                             ^

/tmp/vsc40558/gqcp/dev/intel-2019b-Python-3.7.4/gqcp/gqcp/src/Basis/Integrals/Interfaces/LibintInterfacer.cpp(135): error: no instance of constructor "libint2::Shell::Shell" matches the argument list
            argument types are: (const std::vector<double, std::allocator<double>>, {...}, std::array<double, 3UL>)
      libint2::Shell libint_shell (libint_alpha, {libint_contraction}, libint_O);
                                   ^
/data/gent/vo/000/gvo00004/easybuild/CO7/skylake-eth/software/Libint/2.6.0-intel-2019b/include/libint2/shell.h(243): note: this candidate was rejected because mismatch in count of arguments
        Shell(make_unit) :
        ^
/data/gent/vo/000/gvo00004/easybuild/CO7/skylake-eth/software/Libint/2.6.0-intel-2019b/include/libint2/shell.h(127): note: this candidate was rejected because arguments do not match
        Shell(svector<real_t> _alpha,
        ^
/data/gent/vo/000/gvo00004/easybuild/CO7/skylake-eth/software/Libint/2.6.0-intel-2019b/include/libint2/shell.h(112): note: this candidate was rejected because mismatch in count of arguments
        Shell(Shell&& other) noexcept :
        ^
/data/gent/vo/000/gvo00004/easybuild/CO7/skylake-eth/software/Libint/2.6.0-intel-2019b/include/libint2/shell.h(110): note: this candidate was rejected because mismatch in count of arguments
        Shell(const Shell&) = default;
        ^
/data/gent/vo/000/gvo00004/easybuild/CO7/skylake-eth/software/Libint/2.6.0-intel-2019b/include/libint2/shell.h(109): note: this candidate was rejected because mismatch in count of arguments
        Shell() = default;
        ^

/tmp/vsc40558/gqcp/dev/intel-2019b-Python-3.7.4/gqcp/gqcp/src/Basis/Integrals/Interfaces/LibintInterfacer.cpp(197): error: no suitable user-defined conversion from "libint2::svector<libint2::Shell::real_t={double}>" to "std::vector<double, std::allocator<double>>" exists
      std::vector<double> exponents = libint_shell_copy.alpha;
                                      ^

/tmp/vsc40558/gqcp/dev/intel-2019b-Python-3.7.4/gqcp/gqcp/src/Basis/Integrals/Interfaces/LibintInterfacer.cpp(205): error: no suitable user-defined conversion from "const libint2::svector<libint2::Shell::real_t={double}>" to "std::vector<double, std::allocator<double>>" exists
          std::vector<double> coefficients = libint_contraction.coeff;
```

### PR DESCRIPTION
**Pull request by guacke**
**Short description**

In this PR, we will refactor the libint support from 2.4.2 to 2.6.

**Related issues**

This PR closes #547.

Other related issues: #814, #685, #175, #281, #362, #676, ...

### CODE REVIEW

**Comment by lelemmen** [comment]
@guacke It seems that the fixes for libint v2.6 were pretty minor. Should we address the other issues first, before merging this PR?

**Comment by guacke** [comment]
@lelemmen Great! I will update:

- [ ] conda
- [ ] docker
- [ ] easybuild

@dariatols This can cause temporary instabilities in CI/CD.

**Comment by guacke** [comment]
@lelemmen Could you look at the failing conda-ci-cd test for ubuntu-18.04, Python 3.6?

```
/usr/share/miniconda/envs/packaging/conda-bld/gqcp_1614698649365/work/gqcp/src/Basis/Integrals/Interfaces/LibintInterfacer.cpp:124: error: could not convert 'libint_coeff' from 'const std::vector<double>' to 'libint2::svector<double>' {aka 'boost::container::small_vector<double, 6, void, void>'}
  124 |     libint2::Shell::Contraction libint_contraction {libint_l, libint_pure, libint_coeff};
      | 
```

**Comment by guacke** [comment]
EasyBuild has trouble finding MKL (using the Hubbard example https://gqcg.github.io/GQCP/examples/Hubbard.html):

```
INTEL MKL ERROR: /apps/gent/CO7/skylake-ib/software/imkl/2019.5.281-iimpi-2019b/mkl/lib/intel64/libmkl_avx512.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.
```

- [ ] Add Hubbard Python test

**Comment by lelemmen** [comment]
> @lelemmen Could you look at the failing conda-ci-cd test for ubuntu-18.04, Python 3.6?
> 
> ```
> /usr/share/miniconda/envs/packaging/conda-bld/gqcp_1614698649365/work/gqcp/src/Basis/Integrals/Interfaces/LibintInterfacer.cpp:124: error: could not convert 'libint_coeff' from 'const std::vector<double>' to 'libint2::svector<double>' {aka 'boost::container::small_vector<double, 6, void, void>'}
>   124 |     libint2::Shell::Contraction libint_contraction {libint_l, libint_pure, libint_coeff};
>       | 
> ```

@guacke Conda seems to be building `GQCP:develop` (see [line 615](https://github.com/GQCG/GQCP/runs/2014390220#step:6:615)), which doesn't include the libint-v2.6 fixes yet.

**Comment by guacke** [comment]
Easybuild is functional. Pre-merge setup:
- [ ] 1. dockerhub: update gqcp-dev:latest with gqcp-dev:libint on GQCG-oss/dockerfiles
- [ ] 2. conda: update meta.yaml to git_tag of develop
- [ ] 3. easybuild: point to develop branch

These actions will temporarily destroy the CI/CD of all existing branches, including this one. Commit 1791866 shows that checks are ok. After merge with develop, all existing branches should rebase on master. Furthermore, all existing users of the gqcp-dev docker containers should update after merge to the latest version of this container.

**Comment by lelemmen** [comment]
@guacke It seems that we're making good progress on these DevOps-related issues.

I'm a bit confused, though, regarding your latest comment. The list you've provided, are those things that still have to be done, or are already done?

**Comment by guacke** [comment]
At this stage, the checks of commit 1791866 show that the CI/CD _should_ work after merge with develop. For the latest commit 6d87a80, the 'Build and test' is the only test that should succeed as this test is building this branch in the new gqcp-dev container.

**Pull request merged**
