### PR TITLE
Refactor GQCP-dev support

### PR DESCRIPTION
**Pull request by guacke**
**Short description**

In this PR, I will refactor GQCP-dev support such that we can easily change the underlying development environment.

**Related issues**

Hanging kernel issues with Numpy and Scipy.

**To do**

- [ ] Implement a unit test for GQCP-dev that checks whether Numpy matrices can be inverted.

Tagging @AaronDC60 and @xdvriend.

### CODE REVIEW

**Comment by guacke** [comment]
Currently, I have set GQCP docker to **not** build directly from the GQCP-dev image, but instead build the development environment itself. This allows for easier testing as no development version of GQCP-dev have to be pushed to Dockerhub. On the other hand, this implies that the developers have to keep both Docker files 'in check'. Related issue on StackExchange: https://stackoverflow.com/questions/36362233/can-a-dockerfile-extend-another-one

**Comment by guacke** [comment]
Dependencies are not resolving, despite previous successful tests. Refactor Conda invocation.

**Comment by guacke** [comment]
Numpy matrix inversion is working on my system. Committing to develop. @AaronDC60 Can you check that matrix inversion also works on your end when GA CI/CD has finished on develop?

**Comment by AaronDC60** [comment]
> Numpy matrix inversion is working on my system. Committing to develop. @AaronDC60 Can you check that matrix inversion also works on your end when GA CI/CD has finished on develop?

@guacke Matrix inversion does not work in singularity.

**Pull request merged**
