### PR TITLE
Bugfix: GIT_SHA1 variable empty in gqcpy.

### PR DESCRIPTION
**Pull request by dariatols**
**Short description**

Because the `version` library was compiled before the `GIT_SHA1` CMake variable was set, making it empty when importing `gqcpy`.

### CODE REVIEW

**Comment by dariatols** [comment]
Screenshot 2021-03-18 at 18 38 51

The `GIT_SHA1` variable is now printed when importing `gqcpy`.

**Comment by lelemmen** [comment]
I see from your screenshot that the code works again. Could you perhaps find a way to unit-test this behavior?

**Comment by dariatols** [comment]
@lelemmen I have included an appropriate test that checks whether or not all version details are empty.

**Review by lelemmen — APPROVED** [review]
Looks like a good fix!

**Pull request merged**
