### PR TITLE
Calculate 1DM with ONVPath API.

### PR DESCRIPTION
**Pull request by dariatols**
**Short description**
The calculation of the one-electron density matrix will be refactored such that it will make use of the `ONVPath` API.

**Related issues**
https://github.com/GQCG/GQCP/issues/687 https://github.com/GQCG/GQCP/issues/648
closes https://github.com/GQCG/GQCP/issues/719

**Don't forget:**
- [ ] if new files are created: update the Doxygen file, the collective gqcp.hpp header and the CMake files

### CODE REVIEW

**Comment by lelemmen** [comment]
I'd like you to test this functionality using another method as well: either using the `SpinResolvedONVBasis` or `SpinResolvedSelectedONVBasis` 1-DM evaluations.

**Comment by lelemmen** [comment]
I've created the issue #719 that is related to this PR. Could you update the body text of this PR to automatically close this issue once this PR is merged?

**Comment by dariatols** [comment]
> I'd like you to test this functionality using another method as well: either using the `SpinResolvedONVBasis` or `SpinResolvedSelectedONVBasis` 1-DM evaluations.

This is done now.

**Comment by lelemmen** [comment]
Closed in favor of #783.

**Pull request closed without merging**
