### PR TITLE
Update API's in example notebooks

### LINKED ISSUE #937: Update example notebooks
`GQCP` has undergone some API transformations, which should be reflected in the example notebooks in order for them to correctly run again.

### PR DESCRIPTION
**Pull request by xdvriend**
**Short description**

This PR will update the API's used in the example notebooks for the GQCP website.

**Related issues**

closes #937

### CODE REVIEW

**Comment by xdvriend** [comment]
@guacke Could you review or approve this PR? It updates all notebook API's for the website to the current ones, but in line with issue #872, it also added the python bindings for CI in seniority zero basis, in order to perform DOCI calculations in the corresponding example notebook. 

Otherwise, starting on issue #872 would lead to conflicts.

Note: The complex RHF cells in the example notebook are not executed as the bug fix for complex RHF was performed after this PR was already opened. I'll run the cells in a subsequent PR, in order to get everything on the website working neatly.

EDIT: I have no idea why the conda builds are suddenly failing.

**Comment by guacke** [comment]
@xdvriend Can you rebase on develop to fix the conda issues?

**Comment by xdvriend** [comment]
@guacke, The rebase did indeed fix the issues! I also used this rebase to execute the complex RHF cells in the notebook, as the rebase fixed the bug on this ranch as well.

**Comment by xdvriend** [comment]
@guacke Can I now merge this PR? That would allow me to start working on the required changes for OO-DOCI in between my NOCI PR's.

**Review by dariavh — APPROVED** [review]

**Pull request merged**
