### PR TITLE
AP1roG as QCModel/QCMethod

### LINKED ISSUE #492: Implement pCCD/AP1roG as QCMethod
**Describe a change that would improve the code base**
In order to maintain uniformity among quantum chemical methods, it would be a good idea to implement pCCD/AP1roG as a `QCMethod`.

### LINKED ISSUE #493: Implement pCCD/AP1roG bindings
**Describe the feature you'd like**
It would support our view of 'reproducible results' if we had pCCD/AP1roG Python bindings.

**Describe what the current code offers in relation to what it lacks**
The C++ code already exists, it's merely the bindings that should be implemented.

**Additional context**
This is best started only after #492.

### LINKED ISSUE #496: Implement Python bindings for OO-pCCD
**Describe the feature you'd like**
It would support our view of 'reproducible results' if we had OO-pCCD Python bindings.

**Describe what the current code offers in relation to what it lacks**
The C++ code already exists, it's merely the bindings that should be implemented.

**Additional context**
This is best started only after #494 and #492.

### PR DESCRIPTION
**Pull request by lelemmen**
**Short description**
This PR will refactor AP1roG as QCModel/QCMethod.

**Related issues**
This PR:
- [x] closes #492;
- [x] closes #493;
- [x] closes #496.

**Don't forget:** 
- [x] if new files are created: update the Doxygen file, the collective gqcp.hpp header and the CMake files
- [x] update the documentation on [our website](https://github.com/GQCG/gqcg.github.io) and check if new Python bindings should be added

### CODE REVIEW

**Comment by lelemmen** [comment]
@guacke The `IntegralCalculator` test fails again. Do you remember what you did to resolve the previous failures?

**Comment by guacke** [comment]
@lelemmen In the latest test the `IntegralCalculator` seems to be working again. Only the most recently deployed conda packages do not suffer from the problem mentioned above, so maybe the latest tests purged the cache?

**Comment by guacke** [comment]
@lelemmen The IntegralCalculator test seems to fail (currently) inexplicably in some cases. I will open a PR to address this issue.

**Comment by lelemmen** [comment]
@guacke What's our policy for 'ignoring' the IntegralCalculator test?

**Pull request merged**
