### PR TITLE
Implement complex GHF bindings.

### LINKED ISSUE #645: Complex GHF python bindings
**Describe the feature you'd like**
For GHF, using complex values is sometimes a necessity. It would be useful to include this feature in the python bindings.

**Describe what the current code offers in relation to what it lacks**
The current GHF python bindings only support real valued GHF.

### PR DESCRIPTION
**Pull request by lelemmen**
This PR closes #645.

**Don't forget:**
- [x] if new files are created: update the Doxygen file, the collective gqcp.hpp header and the CMake files

### CODE REVIEW

**Review by xdvriend — APPROVED** [review]
Awesome addition to the code, This PR is good to go!

A small question maybe, how would we go about actually adding complex perturbation to the calculation? I'm guessing transforming the spinor basis or the Hamiltonian? 

I'd be happy to add this functionality to the other HF methods as well, just make an issue or let me know! 😄

**Comment by guacke** [comment]
@lelemmen Apparently, external pull requests do not have access to the secrets needed for the Conda workflow [1]. Fix: push your branch to GQCP and then do a PR from that branch.

[1] https://github.community/t/feature-request-allow-secrets-in-approved-external-pull-requests/18071

**Comment by lelemmen** [comment]
> A small question maybe, how would we go about actually adding complex perturbation to the calculation? I'm guessing transforming the spinor basis or the Hamiltonian?

If I'm interpreting this correctly: adding a complex-valued perturbation would be done through the addition of a complex one- or two-electron operator to the Hamiltonian, and then doing calculations with that perturbed Hamiltonian. Is that something you're interested in? If so, let me know! There are a couple of things that should be added to the library before doing these kinds of calculations.

> I'd be happy to add this functionality to the other HF methods as well, just make an issue or let me know! 😄

Could you create these issues and fill up the product backlog for symmetries and constraints? I'm sure this will be needed for the "thesis blog post" #818.



> @lelemmen Apparently, external pull requests do not have access to the secrets needed for the Conda workflow [1]. Fix: push your branch to GQCP and then do a PR from that branch.
> 
> [1] https://github.community/t/feature-request-allow-secrets-in-approved-external-pull-requests/18071

Ah, I didn't know that, but that sounds pretty reasonable. I'll use GQCP instead of my own fork during my workflow from now on.

**Comment by xdvriend** [comment]
> If I'm interpreting this correctly: adding a complex-valued perturbation would be done through the addition of a complex one- or two-electron operator to the Hamiltonian, and then doing calculations with that perturbed Hamiltonian. Is that something you're interested in? If so, let me know! There are a couple of things that should be added to the library before doing these kinds of calculations.

Yes, that's exactly what I meant! I shared a screenshot in the GQCP MS Teams channel where I was able to perform a complex GHF calculation and find the stable complex solution. I used the functionality to add steps to the solver algorithm to add a step that added a complex perturbation to the initial density matrix (which is how I did it in my python prototype) and then continued the algorithm as normal.

But, in my opinion it would be cleaner to indeed enable the perturbation to happen on the Hamiltonian and then use that perturbed Hamiltonian for the further SCF procedure. If you think this is a good idea, I would be more then interested to help implement the necessary components! 😄 

> Could you create these issues and fill up the product backlog for symmetries and constraints? I'm sure this will be needed for the "thesis blog post" #818.

Yes I'll get to it!

**Pull request merged**
