### PR TITLE
Bugfix: refactor to new GA api (closes #800).

### LINKED ISSUE #800: Conda builds are failing
**Describe the bug**
Our GitHub Actions are failing due to conda.

**Screenshots and logs**

Schermafbeelding 2020-11-20 om 13 58 15

**Additional context**
See the [GitHub Action](https://github.com/GQCG/GQCP/actions/runs/374309831).

@GQCG/devops-developers

### PR DESCRIPTION
**Pull request by guacke**
**Short description**
This PR refactors CI support by taking the new API for Github Actions into account.

**Related issues**
Issue #800.

**Additional context**
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

### CODE REVIEW

**Comment by guacke** [comment]
Reminder: 
- [ ] set up GA 'on' paths correctly before merge

**Comment by guacke** [comment]
@lelemmen @xdvriend @dariatols This PR fixes the current issues with CI. Please rebase all current PRs on develop, after this PR has been merged, in order to enable CI on those branches.

**Review by xdvriend — APPROVED** [review]
Nice, thank you for looking into this!

**Comment by dariatols** [comment]
Thanks!

**Pull request merged**
