### PR TITLE
Feature/precompiled headers

### PR DESCRIPTION
**Pull request by guacke**
This pull request will speed up the compilation by using precompiled headers for the unit tests.

### CODE REVIEW

**Comment by guacke** [comment]
@lelemmen This PR causes g_libcint to deviate from g_libint2 in boost test case libcint_vs_libint2_H2O_STO_3G in AOBasis_test. I am using the conda installer of Libcint. Could you check that you also have these deviation? If so, I will write our own conda installer of the latest version of Libcint.

**Comment by lelemmen** [comment]
@guacke I don't have any problems on my machine: it's using `0bc0327` from the libcint library.

**Comment by guacke** [comment]
@lelemmen Ok, thanks. I will try to fix this issue on a separate branch. This branch speeds up the build on Travis from 35 min. to around 20 min (including rebuild of cache).

**Comment by guacke** [comment]
The libcint problem only seems to occur on my machine. As such, I have re-enabled the relevant AObasis tests.

**Comment by lelemmen** [comment]
@guacke Could you first rebase onto develop? It seems some of the changes in this PR are already in develop.

**Pull request merged**
