### PR TITLE
FindBLAS is bugged for static linking to MKL. Re-implement FindMKL.

### PR DESCRIPTION
**Pull request by guacke**
This PR is aimed at improving the build procedure on the cluster.

### CODE REVIEW

**Comment by guacke** [comment]
This PR successfully compiles on the cluster and leads to fully functioning Python bindings.

**Comment by lelemmen** [comment]
> This PR successfully compiles on the cluster and leads to fully functioning Python bindings.

I can confirm that I also have functioning Python bindings when I use this branch locally.

**Comment by guacke** [comment]
As the main production environment are the HPC clusters and the MKL enabled code compiles successfully there, I have disabled MKL support in Travis in this PR (where MKL remains an issue).

**Comment by guacke** [comment]
I will address the change to the .travis.yml file in a different PR (I first have to resolve a gqcgmeta dependency).

**Pull request merged**
