### PR TITLE
Feature/bindings refactor

### PR DESCRIPTION
**Pull request by guacke**
This PR is aimed at resolving issue #340 .

### CODE REVIEW

**Comment by lelemmen** [comment]
I think I had been doing my CMake commands wrong: I couldn't find the Pybind11 config file. When I use `-DCMAKE_PREFIX_PATH=~/miniconda/envs/gqcp` (where I installed all the dependencies: thank you @guacke and conda), CMake doesn't complain anymore.

**Comment by lelemmen** [comment]
I think we should finalize our decision on gqcpy vs pygqcp. Vote 🚀  for gqcpy and 👀 for pygqcp.

**Comment by lelemmen** [comment]
I believe the last couple of commits close #340. Since this PR is much more mature than the other one (#334), can it be closed, @guacke?

**Comment by guacke** [comment]
PR #334 is currently being used to render the cluster installation error free. I will signal when this is the case.

**Comment by lelemmen** [comment]
This branch was merged into #315.

**Pull request closed without merging**
