### PR TITLE
Move gqcp-dev entirely to Docker

### LINKED ISSUE #934: Problems with building GQCP
**Describe the bug**
When I try to build GQCP, either locally or within a docker container, I'm encountering some issues. 

*Locally*
After updating boost and Libint (to 1.73 and 2.6.0 respectively) I got warnings concerning the following implementation:

`bool areIntegralsAllZero() const { return false; }`
(However I thought these could be solved by marking the function with `override`, so I tried that. The build now continued without warnings.)

Subsequently, the build halts at the following point:
Screenshot 2021-04-06 at 11 31 25

*Docker*
After pulling the latest docker container and setting the cmake options as shown in the documentation on the GQCP website, I get the following error when trying to build GQCP:
Screenshot 2021-04-06 at 11 33 21

**Operating system**
 - OS: Big Sur
 - Version 11.2.3

### PR DESCRIPTION
**Pull request by guacke**
**Short description**

This PR will remove the ability the ability to install gqcp-dev through Conda, as:
-  the respective environment.yml is too costly to maintain when users will mostly be using `gqcp`.
- a fully functioning and configured development environment is most easily set up using Docker.

**Related issues**

closes #934

**To do**

- [x] Update devcontainer and remove `Setting up VSCode` from documentation.

### CODE REVIEW

**Comment by guacke** [comment]
@xdvriend Can you check that, once you have opened the respective devcontainer for this branch, the CMake extensions have been installed and preconfigured. I.e. `Clean reconfigure projects` etc. should work out of the box.

**Comment by xdvriend** [comment]
> @xdvriend Can you check that, once you have opened the respective devcontainer for this branch, the CMake extensions have been installed and preconfigured. I.e. `Clean reconfigure projects` etc. should work out of the box.

So far so good, the build seems to continue in the new docker container. I'll green-light this PR if the build is successful.

**Review by xdvriend — APPROVED** [review]
The build in the new docker container succeeds. There are some warnings generated, but this is due to an implementation and I know how to fix it. So we can merge this PR, and I'll do a bug fix for the warnings afterwards. 

Thank you for the help!

**Comment by guacke** [comment]
@xdvriend Could you refactor the [Developer documentation](https://gqcg.github.io/GQCP/developer-documentation/getting-started.html) further after I have merged this PR? I would suggest to 

- [ ] Start from the Docker container to get started developing GQCP.
- [ ] Add an additional section: Custom builds of GQCP. This should detail the CMake options in those cases where CMake needs be called from the command line (i.e. Singularity).

**Pull request merged**
